<a href="https://colab.research.google.com/github/varunpothu/Applied_Data_Science-Assignment_1/blob/main/Kaggle_Challenge_Notebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **KAGGLE CHALLENGE** : ( TEAM - 5 )


---
**Team Members** :

1.	Varun Pothu – 21080409 – vp22acb@herts.ac.uk
2.	Balaji Pothuganti – 22023213 – bp22abc@herts.ac.uk
3.	Nikhitha Manika – 22007583 – nm22acl@herts.ac.uk
4.	Deepika Cherupally – 22031854 – dc22abs@herts.ac.uk
5.	Dhana Srivalli Golukonda – 21087223 – dg22abc@herts.ac.uk
6.	Bharath Kumar Savarapu – 22018647 – bs22abu@herts.ac.uk
7.	Anish Teku – 22018647 – at22aej@herts.ac.uk

---

---
> **AIM OF THE PROJECT**
---
> The aim of this assignment is to develop a statistical or machine learning model to predict whether passengers on the Spaceship Titanic were transported to an alternate dimension during a collision with a spacetime anomaly. The model will be trained on a provided dataset and evaluated through a Kaggle Challenge. The objective is to apply and demonstrate knowledge of research methods in data science, including data exploration, model development, and critical analysis of results.

---
> **PROBLEM STATEMENT**

---
> In the year 2912, the Spaceship Titanic, carrying almost 13,000 passengers to newly habitable exoplanets, collided with a spacetime anomaly, causing nearly half of the passengers to be transported to an alternate dimension. Using personal records from the ship's damaged computer system, the task is to predict which passengers were transported to the alternate dimension.

* This prediction will assist rescue crews in retrieving the lost passengers and changing history.

* The challenge involves exploring and visualizing the data, building and customizing a predictive model, and presenting the findings collaboratively as a team.

---
> **DATASET DESCRIPTION**
---

The dataset contains personal records of passengers from the Spaceship Titanic to predict if they were transported to an alternate dimension. The training set (train.csv) includes 8,700 records, and the test set (test.csv) includes 4,300 records. Each record features unique passenger IDs, home planets, cryo-sleep status, cabin details, destination, age, VIP status, and spending amounts on various amenities. The target variable, Transported, indicates if a passenger was transported to another dimension. The sample submission file (sample_submission.csv) shows the required prediction format.

```
DATASET LINK:
https://www.kaggle.com/competitions/spaceship-titanic
```
[LINK FOR DATASET](https://www.kaggle.com/competitions/spaceship-titanic)

---

## Importing Libraries

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

## Loading Data

In [ ]:
import pandas as pd
data = "https://raw.githubusercontent.com/7PAM2015-0509-2023-GROUP5/Kaggle_Challenge/main/train.csv"
df = pd.read_csv(data)
df.head()

,PassengerId,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name,Transported
0,0001_01,Europa,False,B/0/P,TRAPPIST-1e,39.0,False,0.0,0.0,0.0,0.0,0.0,Maham Ofracculy,False
1,0002_01,Earth,False,F/0/S,TRAPPIST-1e,24.0,False,109.0,9.0,25.0,549.0,44.0,Juanna Vines,True
2,0003_01,Europa,False,A/0/S,TRAPPIST-1e,58.0,True,43.0,3576.0,0.0,6715.0,49.0,Altark Susent,False
3,0003_02,Europa,False,A/0/S,TRAPPIST-1e,33.0,False,0.0,1283.0,371.0,3329.0,193.0,Solam Susent,False
4,0004_01,Earth,False,F/1/S,TRAPPIST-1e,16.0,False,303.0,70.0,151.0,565.0,2.0,Willy Santantines,True

In [3]:
data_test = "https://raw.githubusercontent.com/7PAM2015-0509-2023-GROUP5/Kaggle_Challenge/main/test.csv"
df_test = pd.read_csv(data_test)
df_test

,PassengerId,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name
0,0013_01,Earth,True,G/3/S,TRAPPIST-1e,27.0,False,0.0,0.0,0.0,0.0,0.0,Nelly Carsoning
1,0018_01,Earth,False,F/4/S,TRAPPIST-1e,19.0,False,0.0,9.0,0.0,2823.0,0.0,Lerome Peckers
2,0019_01,Europa,True,C/0/S,55 Cancri e,31.0,False,0.0,0.0,0.0,0.0,0.0,Sabih Unhearfus
3,0021_01,Europa,False,C/1/S,TRAPPIST-1e,38.0,False,0.0,6652.0,0.0,181.0,585.0,Meratz Caltilter
4,0023_01,Earth,False,F/5/S,TRAPPIST-1e,20.0,False,10.0,0.0,635.0,0.0,0.0,Brence Harperez
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4272,9266_02,Earth,True,G/1496/S,TRAPPIST-1e,34.0,False,0.0,0.0,0.0,0.0,0.0,Jeron Peter
4273,9269_01,Earth,False,NaN,TRAPPIST-1e,42.0,False,0.0,847.0,17.0,10.0,144.0,Matty Scheron
4274,9271_01,Mars,True,D/296/P,55 Cancri e,NaN,False,0.0,0.0,0.0,0.0,0.0,Jayrin Pore
4275,9273_01,Europa,False,D/297/P,NaN,NaN,False,0.0,2680.0,0.0,0.0,523.0,Kitakan Conale
4276,9277_01,Earth,True,G/1498/S,PSO J318.5-22,43.0,False,0.0,0.0,0.0,0.0,0.0,Lilace Leonzaley

## EDA (Exploratory data analysis)

## Data Pre-Processing

## Data Modelling

## Analysis & XAI

## Data Predictions

## Kaggle Submisson File